packages:
  - apps/*
  - packages/*

catalogMode: prefer

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0

overrides:
  vite@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

allowBuilds:
  "@opencode-ai/cli": true
  msgpackr-extract: false

minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.3.0"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.3.0"
  - "@voidzero-dev/vite-plus-darwin-x64@0.3.0"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.0"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.3.0"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.3.0"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.3.0"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.0"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.3.0"
  - "vite-plus@0.3.0"
  - "@opencode-ai/cli-darwin-arm64@0.0.0-beta-18050"
  - "@opencode-ai/cli-darwin-x64-baseline@0.0.0-beta-18050"
  - "@opencode-ai/cli-darwin-x64@0.0.0-beta-18050"
  - "@opencode-ai/cli-linux-arm64-musl@0.0.0-beta-18050"
  - "@opencode-ai/cli-linux-arm64@0.0.0-beta-18050"
  - "@opencode-ai/cli-linux-x64-baseline-musl@0.0.0-beta-18050"
  - "@opencode-ai/cli-linux-x64-baseline@0.0.0-beta-18050"
  - "@opencode-ai/cli-linux-x64-musl@0.0.0-beta-18050"
  - "@opencode-ai/cli-linux-x64@0.0.0-beta-18050"
  - "@opencode-ai/cli-windows-arm64@0.0.0-beta-18050"
  - "@opencode-ai/cli-windows-x64-baseline@0.0.0-beta-18050"
  - "@opencode-ai/cli-windows-x64@0.0.0-beta-18050"
  - "@opencode-ai/cli@0.0.0-beta-18050"
  - "@opencode-ai/client@0.0.0-beta-18050"
  - "@opencode-ai/protocol@0.0.0-beta-18050"
  - "@opencode-ai/schema@0.0.0-beta-18050"
  - "@types/react-dom@19.2.5"
