packages:
  - apps/*
  - packages/*

catalogMode: prefer

catalog:
  "@effect/tsgo": 0.38.0
  "@opencode-ai/cli": 0.0.0-beta-18155
  "@opencode-ai/client": 0.0.0-beta-18155
  "@opencode-ai/ui": 0.0.0-beta-18155
  "@oxlint/plugins": 1.79.0
  "@solidjs/meta": ^0.29.4
  "@storybook/addon-a11y": 10.5.10
  "@testing-library/jest-dom": 6.9.1
  electron: 42.3.3
  electron-vite: 6.0.0-beta.1
  jsdom: ^30.0.1
  oxlint: 1.79.0
  oxlint-tsgolint: 7.0.2001
  solid-js: ^1.9.15
  storybook: 10.5.10
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plugin-solid: 2.11.14
  vite-plus: 0.3.0

overrides:
  vite@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

allowBuilds:
  "@opencode-ai/cli": true
  electron: true
  esbuild: true
  msgpackr-extract: false

minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.3.0"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.3.0"
  - "@voidzero-dev/vite-plus-darwin-x64@0.3.0"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.0"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.3.0"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.3.0"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.3.0"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.0"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.3.0"
  - "vite-plus@0.3.0"
  - "@opencode-ai/cli-darwin-arm64@0.0.0-beta-18155"
  - "@opencode-ai/cli-darwin-x64-baseline@0.0.0-beta-18155"
  - "@opencode-ai/cli-darwin-x64@0.0.0-beta-18155"
  - "@opencode-ai/cli-linux-arm64-musl@0.0.0-beta-18155"
  - "@opencode-ai/cli-linux-arm64@0.0.0-beta-18155"
  - "@opencode-ai/cli-linux-x64-baseline-musl@0.0.0-beta-18155"
  - "@opencode-ai/cli-linux-x64-baseline@0.0.0-beta-18155"
  - "@opencode-ai/cli-linux-x64-musl@0.0.0-beta-18155"
  - "@opencode-ai/cli-linux-x64@0.0.0-beta-18155"
  - "@opencode-ai/cli-windows-arm64@0.0.0-beta-18155"
  - "@opencode-ai/cli-windows-x64-baseline@0.0.0-beta-18155"
  - "@opencode-ai/cli-windows-x64@0.0.0-beta-18155"
  - "@opencode-ai/cli@0.0.0-beta-18155"
  - "@opencode-ai/client@0.0.0-beta-18155"
  - "@opencode-ai/protocol@0.0.0-beta-18155"
  - "@opencode-ai/schema@0.0.0-beta-18155"
  - "@opencode-ai/ui@0.0.0-beta-18155"
  - "@types/node@26.3.0"
  - "@effect/tsgo-darwin-arm64@0.38.0"
  - "@effect/tsgo-darwin-x64@0.38.0"
  - "@effect/tsgo-linux-arm64@0.38.0"
  - "@effect/tsgo-linux-arm@0.38.0"
  - "@effect/tsgo-linux-x64@0.38.0"
  - "@effect/tsgo-win32-arm64@0.38.0"
  - "@effect/tsgo-win32-x64@0.38.0"
  - "@effect/tsgo@0.38.0"
